### ISSUE TITLE
Compiling clap_autocomplete v0.3.0

### ISSUE THREAD

**Issue by taomathart** [Icelk/strange-attractor-renderer#2]
Hello, when compiled it throws the following error:

 Compiling clap_autocomplete v0.3.0
error[E0433]: failed to resolve: could not find `BaseDirectories` in `xdg`
   --> C:\Users\Jusakito\.cargo\registry\src\github.com-1ecc6299db9ec823\clap_autocomplete-0.3.0\src\lib.rs:125:29
    |
125 |             let dirs = xdg::BaseDirectories::new()?;
    |                             ^^^^^^^^^^^^^^^ could not find `BaseDirectories` in `xdg`

**Comment by Icelk** [comment]
Thanks for bringing this to my attention. The issue is with my crate `clap_autocomplete` depending on `xdg`, which doesn't work on Windows. I'll update it and fix the issue. In the meantime, try compiling/running it with the cargo flags `--no-default-features --features png,bin`.

I'll ping you when this is properly fixed :)

**Comment by Icelk** [comment]
I've updated the dependency now. Can you please retry the compilation? No cargo flags should be needed.

**Comment by taomathart** [comment]
> I've updated the dependency now. Can you please retry the compilation? No cargo flags should be needed.

Hello again. Everything is alright now. Thanks a lot

Beautiful attractors!!!

**Comment by Icelk** [comment]
Good to hear. Thank you!
